[workspace]

resolver = "2"

members = ["bls12-381", "eip7594", "kzg-multi-open", "polynomial"]

[workspace.dependencies]
bls12-381 = { path = "./bls12-381" }
polynomial = { path = "./polynomial" }
kzg-multi-open = { path = "./kzg-multi-open" }
