[workspace]

members = [
    "bindings/c",
    "bindings/java/rust_code",
    "bindings/node",
    "bindings/nim/rust_code",
    "bls12_381",
    "eip7594",
    "kzg_multi_open",
    "polynomial",
]

resolver = "2"

[workspace.package]
authors = ["Kevaundray Wedderburn <kev@the.dev>"]
edition = "2021"
license = "MIT"
rust-version = "1.66"
repository = "https://github.com/crate-crypto/peerdas-kzg"


[workspace.dependencies]
bls12_381 = { version = "0.1.0", path = "./bls12_381" }
polynomial = { version = "0.1.0", path = "./polynomial" }
eip7594 = { version = "0.1.0", path = "./eip7594" }
kzg_multi_open = { version = "0.1.0", path = "./kzg_multi_open" }
c_peerdas_kzg = { version = "0.1.0", path = "./bindings/c" }
hex = "0.4.3"
rayon = "1.10.0"
