# On mac, this linker can be installed with `brew install SergioBenitez/osxct/x86_64-unknown-linux-gnu`
[target.x86_64-unknown-linux-gnu]
linker = "x86_64-unknown-linux-gnu-gcc"

# On mac this linker can be installed with:
# - `brew tap messense/homebrew-macos-cross-toolchains`
# - `brew install aarch64-unknown-linux-gnu`
[target.aarch64-unknown-linux-gnu]
linker = "aarch64-unknown-linux-gnu-gcc"
