[package]
name = "c_peerdas_kzg"
version = "0.2.1"
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }
repository = { workspace = true }


[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
libc = "0.2.2"
eip7594 = { workspace = true }

[build-dependencies]
cbindgen = "0.26.0"
