name: Upload Artifacts

on:
  push:
    branches:
      - kw/ci-release-workflow-revamp
  workflow_dispatch:
  pull_request:

jobs:
  upload:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            ref: kw/ci-release-workflow-revamp

      - name: Create example.txt
        run: echo "This is an example file." > example.txt
    
      - name: Install all rust targets needed
        run: .github/scripts/install_all_targets.sh

      - name: Compile all node builds
        run: .github/scripts/compile_all_targets_node.sh

      - name: Compile all java builds 
        run: .github/scripts/compile_all_targets_java.sh
    
      - name: Compile all csharp builds
        run: .github/scripts/compile_all_targets_c_sharp.sh

      - name: Compile all c builds
        run: .github/scripts/compile_all_targets_c.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: example-artifact
          path: example.txt

      - name: Dispatch to test workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: download-and-test.yml
          ref: kw/ci-release-workflow-revamp
          inputs: '{"run_id": "${{ github.run_id }}"}'
          token: ${{ secrets.GITHUB_TOKEN }}
