name: Upload Artifacts

on:
  push:
    branches:
      - kw/ci-release-workflow-revamp
  workflow_dispatch:
  pull_request:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            ref: kw/ci-release-workflow-revamp

      - name: Create example.txt
        run: echo "This is an example file." > example.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: example-artifact
          path: example.txt

      - name: Dispatch to test workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: download-and-test.yml
          ref: kw/ci-release-workflow-revamp
          inputs: '{"run_id": "${{ github.run_id }}"}'
          token: ${{ secrets.GITHUB_TOKEN }}
