name: Download and Process

on:
  pull_request:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'The run ID of the triggering workflow'
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            ref: kw/ci-release-workflow-revamp

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: example-artifact
          path: example.txt
          run-id: ${{ github.event.inputs.run_id }}

      - name: Display file content
        run: cat example.txt
