name: Download and Process

on:
  pull_request:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'The run ID of the triggering workflow'
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            ref: kw/ci-release-workflow-revamp
      - name: Make a new dir called foobar
        run: mkdir foobar
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: foobar
          github-token: ${{ secrets.WORKFLOW_SHARING_TOKEN }}
          # name: example-artifact
          # path: example.txt
          run-id: ${{ inputs.run_id }}
      
      - name: Display structure of downloaded files
        run: ls -R foobar

      # - name: Display file content
      #   run: cat example.txt
