name: Release

permissions:
  contents: write
  pull-requests: write
  actions: write

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-please:
    name: Create Release
    outputs:
      release-pr: ${{ steps.release.outputs.pr }}
      tag-name: ${{ steps.release.outputs.tag_name }}

    runs-on: ubuntu-latest
    steps:
      - name: Run release-please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_TOKEN }}

  publish-rust-crates:
        name: Publish necessary rust crates
        needs: [release-please]
        if: ${{ needs.release-please.outputs.tag-name }}
        runs-on: ubuntu-latest
        steps:
            -   name: Dispatch to publish workflow
                uses: benc-uk/workflow-dispatch@v1
                with:
                    workflow: release-rust-crates.yml
                    ref: master
                    inputs: '{ "ref": "${{ needs.release-please.outputs.tag-name }}" }'
                    token: ${{ secrets.RELEASE_TOKEN }}

  publish-node-bindings:
        name: Publish node bindings
        needs: [release-please]
        if: ${{ needs.release-please.outputs.tag-name }}
        runs-on: ubuntu-latest
        steps:
            -   name: Dispatch to publish workflow
                uses: benc-uk/workflow-dispatch@v1
                with:
                    workflow: release-node-bindings.yml
                    ref: master
                    inputs: '{ "ref": "${{ needs.release-please.outputs.tag-name }}", "release-type": "release" }'
                    token: ${{ secrets.RELEASE_TOKEN }}

  publish-java-bindings:
        name: Publish java bindings
        needs: [release-please]
        if: ${{ needs.release-please.outputs.tag-name }}
        runs-on: ubuntu-latest
        steps:
            -   name: Dispatch to publish workflow
                uses: benc-uk/workflow-dispatch@v1
                with:
                    workflow: release-java-bindings.yml
                    ref: master
                    inputs: '{ "ref": "${{ needs.release-please.outputs.tag-name }}" }'
                    token: ${{ secrets.RELEASE_TOKEN }}

  publish-csharp-bindings:
        name: Publish c# bindings
        needs: [release-please]
        if: ${{ needs.release-please.outputs.tag-name }}
        runs-on: ubuntu-latest
        steps:
            -   name: Dispatch to publish workflow
                uses: benc-uk/workflow-dispatch@v1
                with:
                    workflow: release-csharp-bindings.yml
                    ref: master
                    inputs: '{ "ref": "${{ needs.release-please.outputs.tag-name }}" }'
                    token: ${{ secrets.RELEASE_TOKEN }}

  publish-nim-bindings:
        name: Publish nim bindings
        needs: [release-please]
        if: ${{ needs.release-please.outputs.tag-name }}
        runs-on: ubuntu-latest
        steps:
            -   name: Dispatch to publish workflow
                uses: benc-uk/workflow-dispatch@v1
                with:
                    workflow: release-nim-bindings.yml
                    ref: master
                    inputs: '{ "ref": "${{ needs.release-please.outputs.tag-name }}" }'
                    token: ${{ secrets.RELEASE_TOKEN }}