name: Publish C# bindings

on:
  workflow_dispatch:
    inputs:
      ref:
        description: The reference (branch/tag/commit) to checkout
        required: true

jobs:
  publish:
    name: Publish C# bindings
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@1.74.1

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Strip leading v from tagged version
      # Strip the leading v from the tag name. It should be of the form v0.1.2
      # dotnet requires it to be of the form 0.1.2
        run: echo "VERSION=${{ inputs.ref }}" | sed 's/^v//' >> $GITHUB_ENV

      - name: Run compile script
        run: |
          chmod +x scripts/compile_all_targets_c_sharp.sh
          scripts/compile_all_targets_c_sharp.sh

      - name: Package with dotnet pack
        working-directory: bindings/csharp
        run: dotnet pack -c release --no-restore -o nupkgs -p:Version=${{ env.VERSION }} -p:ContinuousIntegrationBuild=true
        
      - name: Publish to Nuget
        working-directory: bindings/csharp
        run: dotnet nuget push nupkgs/*.nupkg --api-key ${{ secrets.NUGET_RELEASE_TOKEN }} --source https://api.nuget.org/v3/index.json
