name: Publish node bindings

on:
  workflow_dispatch:
    inputs:
      ref:
        description: The reference (branch/tag/commit) to checkout
        required: true

jobs:
  publish:
    name: Publish node bindings
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: TODO node bindings code
        run: |
              echo "Code to publish node bindings needs to be setup reference input: ${{ inputs.ref }}"
