name: Release

permissions:
  contents: write
  pull-requests: write
  actions: write

on:
  push:
    branches:
      - master

jobs:
  release-please:
    name: Create Release
    outputs:
      release-pr: ${{ steps.release.outputs.pr }}
      tag-name: ${{ steps.release.outputs.tag_name }}

    runs-on: ubuntu-latest
    steps:
      - name: Run release-please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_TOKEN }}

  publish-rust-crates:
        name: Publish necessary rust crates
        needs: [release-please]
        if: ${{ needs.release-please.outputs.tag-name }}
        runs-on: ubuntu-latest
        steps:
            -   name: Dispatch to publish workflow
                uses: benc-uk/workflow-dispatch@v1
                with:
                    workflow: rust-crates-publish.yml
                    ref: master
                    inputs: '{ "ref": "${{ needs.release-please.outputs.tag-name }}" }'
                    token: ${{ secrets.RELEASE_TOKEN }}
