name: Cross-platform Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-gnu

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        override: true

    - name: Install cargo-binstall
      uses: taiki-e/install-action@cargo-binstall

    - name: Install Zig
      if: ${{ matrix.os != 'windows-latest' }}
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.10.1

    - name: Install cargo-zigbuild
      if: ${{ matrix.os != 'windows-latest' }}
      run: cargo binstall --no-confirm cargo-zigbuild

    - name: Install cargo-xwin
      if: ${{ matrix.os == 'windows-latest' }}
      run: cargo binstall --no-confirm cargo-xwin

    - name: Build with cargo-zigbuild
      if: ${{ matrix.os != 'windows-latest' }}
      run: cargo zigbuild --target ${{ matrix.target }} --release

    - name: Build with cargo-xwin
      if: ${{ matrix.os == 'windows-latest' }}
      run: cargo xwin build --target ${{ matrix.target }} --release

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.target }}
        path: target/${{ matrix.target }}/release/*