name: Test Java bindings

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    env:
      GRADLE_OPTS: "--scan-agreement=yes"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run compile script
        run: ./scripts/compile.sh
        shell: bash

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build
        working-directory: bindings/java/java_code

      - name: Run Gradle tests
        run: ./gradlew test --scan
        working-directory: bindings/java/java_code
