name: Cross-platform Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-apple-darwin
          - x86_64-apple-darwin
          # - x86_64-pc-windows-gnu

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        override: true

    - name: Install llvm-preview-tools
      if: ${{ endsWith(matrix.target, 'windows-gnu') }}
      run: rustup component add llvm-tools-preview 
    - name: Install cargo-binstall
      uses: taiki-e/install-action@cargo-binstall

    - name: Install Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.10.1

    - name: Install cargo-zigbuild
      run: cargo binstall --no-confirm cargo-zigbuild

    - name: Install cargo-xwin
      run: cargo binstall --no-confirm cargo-xwin

    - name: Build with cargo-zigbuild (non-Windows)
      if: ${{ !endsWith(matrix.target, 'windows-gnu') }}
      run: cargo zigbuild --target ${{ matrix.target }} --release

    - name: Build with cargo-xwin (Windows)
      if: ${{ endsWith(matrix.target, 'windows-gnu') }}
      run: cargo xwin build --target ${{ matrix.target }} --release

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.target }}
        path: target/${{ matrix.target }}/release/*