name: Test Nim bindings

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      # - name: Setup Zig
      #   uses: goto-bus-stop/setup-zig@v2
      
      # - name: Add zigbuild
      #   run: cargo install cargo-zigbuild 

      - name: Run compile script
        run: ./scripts/compile.sh nim
        shell: bash

      - name: Setup Nim
        uses: jiro4989/setup-nim-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          nim-version: '2.0.4'
      
      - name: Install Nimble dependencies
        working-directory: bindings/nim/nim_code
        run: nimble install -Y

      - name: Test Nim project
        working-directory: bindings/nim/nim_code
        run: nimble test -Y --verbose
