name: Test Node bindings

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Dispatch to publish workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
            workflow: release-node-bindings.yml
            ref: master
            inputs: '{ "ref": "${{ github.ref }}", "release-type": "none" }'
            token: ${{ secrets.RELEASE_TOKEN }}
