name: Cross-platform Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-apple-darwin
          - x86_64-apple-darwin
          - x86_64-pc-windows-gnu
          - aarch64-pc-windows-msvc

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        override: true

    - name: Install cargo-binstall
      uses: taiki-e/install-action@cargo-binstall

    - name: Install Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.10.1

    - name: Install cargo-zigbuild
      run: cargo binstall --no-confirm cargo-zigbuild

    - name: Install cargo-xwin
      run: cargo binstall --no-confirm cargo-xwin

    - name: Set up MinGW (for x86_64 Windows)
      if: ${{ matrix.target == 'x86_64-pc-windows-gnu' }}
      run: sudo apt-get install gcc-mingw-w64-x86-64 -y

    - name: Build with cargo-zigbuild
      # if: ${{ !endsWith(matrix.target, 'windows-gnu') && !endsWith(matrix.target, 'windows-msvc') }}
      run: cargo zigbuild --target ${{ matrix.target }} --release

    # - name: Build with cargo-xwin (Windows)
    #   if: ${{ endsWith(matrix.target, 'windows-gnu') || endsWith(matrix.target, 'windows-msvc') }}
    #   run: cargo zigbuild --target ${{ matrix.target }} --release

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.target }}
        path: target/${{ matrix.target }}/release/*