name: Test Publish Dummy Package to GitHub Packages

on:
  workflow_dispatch:

jobs:
  publish-dummy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Create dummy project and initialize Gradle
      run: |
        mkdir -p src/main/java/org/peerdas/kzg
        echo "package org.peerdas.kzg; public class DummyClass { public static void main(String[] args) { System.out.println(\"Hello from PeerDAS KZG DummyClass\"); } }" > src/main/java/org/peerdas/kzg/DummyClass.java
        
        echo "plugins {
          id 'java'
          id 'maven-publish'
        }
        
        group = 'org.peerdas.kzg'
        version = '0.0.1-SNAPSHOT'
        
        repositories {
          mavenCentral()
        }
        
        publishing {
          repositories {
            maven {
              name = \"GitHubPackages\"
              url = uri(\"https://maven.pkg.github.com/crate-crypto/peerdas-kzg\")
              credentials {
                username = System.getenv(\"GITHUB_ACTOR\")
                password = System.getenv(\"GITHUB_TOKEN\")
              }
            }
          }
          publications {
            gpr(MavenPublication) {
              from(components.java)
            }
          }
        }" > build.gradle

        # Initialize Gradle wrapper
        gradle wrapper

    - name: Publish dummy package
      run: ./gradlew publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}